name: protein_orientation
channels:
  - conda-forge
  - bioconda
  - defaults
  - salilab
  - MDAnalysis
dependencies:
  - attrs=19.3.0
  - biopython=1.76
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cftime=1.1.1.2
  - coverage=5.1
  - curl=7.69.1
  - cycler=0.10.0
  - decorator=4.4.2
  - freetype=2.10.1
  - griddataformats=0.5.0
  - gsd=2.1.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - importlib-metadata=1.6.0
  - joblib=0.14.1
  - jpeg=9c
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libcxx=9.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libssh2=1.8.2
  - llvm-openmp=10.0.0
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mdanalysis=0.20.1
  - mmtf-python=1.1.2
  - more-itertools=8.2.0
  - msgpack-python=1.0.0
  - ncurses=6.1
  - netcdf4=1.5.3
  - networkx=2.4
  - numpy=1.18.1
  - openssl=1.1.1g
  - packaging=20.1
  - pandas=1.0.3
  - patsy=0.5.1
  - pip=20.0.2
  - pluggy=0.13.1
  - py=1.8.1
  - pyparsing=2.4.7
  - pytest=5.4.1
  - pytest-cov=2.8.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2019.3
  - readline=8.0
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - seaborn=0.10.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.30.1
  - statsmodels=0.11.1
  - tk=8.6.10
  - tornado=6.0.4
  - wcwidth=0.1.9
  - wheel=0.34.2
  - xz=5.2.5
  - zipp=3.1.0
  - zlib=1.2.11
